SHELL := /bin/bash

ENV_FILE ?= .env

-include $(ENV_FILE)

ENV ?= tcv
export COMPOSE_PROJECT_NAME ?= $(ENV)
DOCKER_COMPOSE ?= docker compose
COMPOSE_DEV_FILES = -f docker-compose.yml -f docker-compose.dev.yml
COMPOSE_ENV_FILE_ARGS = env_file_args=(); [ ! -f "$(ENV_FILE)" ] || env_file_args=(--env-file "$(ENV_FILE)")
COMPOSE_DEV_DEFAULT_ENV = ADMIN_PASSWORD_HASH=$${ADMIN_PASSWORD_HASH:-} ADMIN_PASSWORD_SALT=$${ADMIN_PASSWORD_SALT:-} SMTP_HOST=$${SMTP_HOST:-maildev} SMTP_PORT=$${SMTP_PORT:-1025} SMTP_SECURE=$${SMTP_SECURE:-false} SMTP_USER=$${SMTP_USER:-} SMTP_PASS=$${SMTP_PASS:-} SMTP_FROM=$${SMTP_FROM:-cv-transpose@sent-tech.local}
COMPOSE_DEV = $(COMPOSE_ENV_FILE_ARGS); $(COMPOSE_DEV_DEFAULT_ENV) $(DOCKER_COMPOSE) "$${env_file_args[@]}" $(COMPOSE_DEV_FILES)

export API_PORT ?= 8686
export UI_PORT ?= 5175
export MAILDEV_SMTP_PORT ?= 1026
export MAILDEV_UI_PORT ?= 1081
export VITE_API_BASE_URL ?= http://localhost:$(API_PORT)/api
export CORS_ALLOWED_ORIGINS ?= http://localhost:$(UI_PORT),http://127.0.0.1:$(UI_PORT),http://ui:5173
export TENANT_S3_BUCKET ?= cv-transpose-config
export TENANT_S3_REGION ?= fr-par
export TENANT_S3_ENDPOINT ?= https://s3.$(TENANT_S3_REGION).scw.cloud
export TENANT_S3_ACCESS_KEY ?= $(shell scw config get access-key 2>/dev/null)
export TENANT_S3_SECRET_KEY ?= $(shell scw config get secret-key 2>/dev/null)
export DEV_TENANT_STORAGE_BACKEND ?= s3
export DEV_TENANT_S3_BUCKET ?= cv-transpose-dev
export DEV_TENANT_S3_REGION ?= fr-par
export DEV_TENANT_S3_ENDPOINT ?= http://minio:9000
export MINIO_ROOT_USER ?= minioadmin
export MINIO_ROOT_PASSWORD ?= minioadmin
export MINIO_API_PORT ?= 9000
export MINIO_CONSOLE_PORT ?= 9001

export API_VERSION    ?= $(shell (git ls-files api core package.json package-lock.json tsconfig.base.json 2>/dev/null || find api core package.json package-lock.json tsconfig.base.json -type f 2>/dev/null) | LC_ALL=C sort | xargs cat 2>/dev/null | sha1sum | sed 's/\(......\).*/\1/')
export API_IMAGE_NAME ?= transpose-cv-api

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show available targets
	@echo "Available targets:"
	@grep -hE '^[a-zA-Z0-9_.-]+:.*?##' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[32m%-25s\033[0m %s\n", $$1, $$2}'

# -----------------------------------------------------------------------------
# Development
# -----------------------------------------------------------------------------

.PHONY: dev-secrets
dev-secrets: ## Generate persistent local development secrets in .env
	@mkdir -p "$$(dirname "$(ENV_FILE)")"
	@touch "$(ENV_FILE)"
	@if grep -Eq '^[[:space:]]*(export[[:space:]]+)?ADMIN_SEED_SECRET=[^[:space:]#]+' "$(ENV_FILE)" && ! grep -Eq '^[[:space:]]*(export[[:space:]]+)?ADMIN_SEED_SECRET=<long_random_secret>' "$(ENV_FILE)"; then \
		echo "ADMIN_SEED_SECRET already set in $(ENV_FILE)"; \
	else \
		secret=$$(openssl rand -hex 32 2>/dev/null || od -An -tx1 -N32 /dev/urandom | tr -d ' \n'); \
		if grep -Eq '^[[:space:]]*(export[[:space:]]+)?ADMIN_SEED_SECRET=' "$(ENV_FILE)"; then \
			perl -0pi -e 's/^[ \t]*(?:export[ \t]+)?ADMIN_SEED_SECRET=.*$$/export ADMIN_SEED_SECRET='"$$secret"'/m' "$(ENV_FILE)"; \
		else \
			{ \
				if [ -s "$(ENV_FILE)" ]; then printf '\n'; fi; \
				printf '# Generated by make dev-secrets for local DB-less admin auth\n'; \
				printf 'export ADMIN_SEED_SECRET=%s\n' "$$secret"; \
			} >> "$(ENV_FILE)"; \
		fi; \
		echo "Generated ADMIN_SEED_SECRET in $(ENV_FILE)"; \
	fi

.PHONY: dev
dev: dev-secrets ## Start UI and API in watch mode
	$(COMPOSE_DEV) up --build -d

.PHONY: up
up: dev-secrets ## Start the full stack in detached mode
	$(COMPOSE_DEV) up --build -d --wait

.PHONY: down
down: ## Stop and remove containers
	$(COMPOSE_DEV) down

.PHONY: ps
ps: ## Show running services
	$(COMPOSE_DEV) ps

.PHONY: logs
logs: ## Show logs for all services
	$(COMPOSE_DEV) logs -f

.PHONY: logs-%
logs-%: ## Show logs for a specific service (e.g., make logs-api)
	$(COMPOSE_DEV) logs -f $*

.PHONY: clean
clean: ## Clean all containers, volumes
	$(COMPOSE_DEV) down -v --remove-orphans

# -----------------------------------------------------------------------------
# Installation
# -----------------------------------------------------------------------------

.PHONY: install-api
install-api: ## Install API dependencies in container
	$(COMPOSE_DEV) exec api npm install $(NPM_LIB)

.PHONY: install-ui
install-ui: ## Install UI dependencies in container
	$(COMPOSE_DEV) exec ui npm install $(NPM_LIB)

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

.PHONY: build
build: build-api ## Build API image for production

.PHONY: build-api
build-api: ## Build API Docker image for production
	TARGET=production $(DOCKER_COMPOSE) build --no-cache api

.PHONY: build-ui
build-ui: ## Build UI locally (SvelteKit static, deployed via GH Pages)
	cd ui && VITE_API_BASE_URL=https://cv-api.sent-tech.ca/api npm run build

# -----------------------------------------------------------------------------
# Type checking
# -----------------------------------------------------------------------------

.PHONY: typecheck-api
typecheck-api: ## Run TypeScript check on API
	$(COMPOSE_DEV) exec api npx tsc --noEmit

.PHONY: typecheck-ui
typecheck-ui: ## Run SvelteKit check on UI
	$(COMPOSE_DEV) exec ui npm run check

.PHONY: typecheck
typecheck: typecheck-api typecheck-ui ## Run all type checks

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------

.PHONY: test-api
test-api: ## Run API unit tests
	$(COMPOSE_DEV) exec api sh -c 'files=$$(find src \( -name "*.test.ts" -o -name "*.spec.ts" \) | sort); if [ -z "$$files" ]; then echo "No API tests found"; exit 0; fi; node --import tsx --test $$files'

.PHONY: test-core-python
test-core-python: ## Run Python core unit tests in Docker (excludes opt-in integration tests)
	docker run --rm --user "$$(id -u):$$(id -g)" -v "$$(pwd):/app" -w /app python:3.12-slim sh -lc 'HOME=/tmp PIP_CACHE_DIR=/tmp/pip-cache python -m pip install --disable-pip-version-check '"'"'cryptography>=45,<46'"'"' '"'"'lxml>=5.2,<6'"'"' '"'"'pypdf>=4.2,<6'"'"' '"'"'pytest>=8.2,<9'"'"' '"'"'pytest-asyncio>=0.23,<1'"'"' && HOME=/tmp PYTHONPATH=/app/core/python PYTHONDONTWRITEBYTECODE=1 python -m pytest -p no:cacheprovider --ignore=core/python/tests/integration core/python/tests'

.PHONY: test-gemini-integration
test-gemini-integration: ## Run Gemini ADK integration smoke (requires GOOGLE_API_KEY env var)
	docker run --rm --user "$$(id -u):$$(id -g)" -e GOOGLE_API_KEY -v "$$(pwd):/app" -w /app python:3.12-slim sh -lc 'HOME=/tmp PIP_CACHE_DIR=/tmp/pip-cache python -m pip install --disable-pip-version-check '"'"'cryptography>=45,<46'"'"' '"'"'lxml>=5.2,<6'"'"' '"'"'pypdf>=4.2,<6'"'"' '"'"'pytest>=8.2,<9'"'"' '"'"'pytest-asyncio>=0.23,<1'"'"' '"'"'google-adk>=1.0,<2'"'"' '"'"'google-genai>=1.0,<2'"'"' && HOME=/tmp PYTHONPATH=/app/core/python PYTHONDONTWRITEBYTECODE=1 python -m pytest -p no:cacheprovider -m integration core/python/tests/integration'

.PHONY: smoke-tenant-e2e
smoke-tenant-e2e: ## Run tenant E2E smoke (TENANT=_default|scalian)
	$(COMPOSE_DEV) exec api sh -c 'TENANT="$(if $(strip $(TENANT)),$(TENANT),_default)" INPUT_FILE="$(if $(strip $(INPUT_FILE)),$(INPUT_FILE),templates/references/cgi_source_example_fictional.docx)" SESSION_PASSWORD="$(if $(strip $(SESSION_PASSWORD)),$(SESSION_PASSWORD),smoke-pass)" API_BASE_URL="$(if $(strip $(API_BASE_URL)),$(API_BASE_URL),http://localhost:8686/api)" PROVIDER="$(PROVIDER)" TARGET_COMPANY="$(TARGET_COMPANY)" TIMEOUT_MS="$(if $(strip $(TIMEOUT_MS)),$(TIMEOUT_MS),180000)" POLL_INTERVAL_MS="$(if $(strip $(POLL_INTERVAL_MS)),$(POLL_INTERVAL_MS),2000)" npx tsx scripts/smoke-tenant-e2e.ts'

.PHONY: analyze-template-docx
analyze-template-docx: ## Analyze a supplier DOCX example into a TemplateContract (PROFILE=..., INPUT_FILE=..., OUTPUT_FILE=...)
	$(COMPOSE_DEV) exec api sh -c 'PROFILE="$(if $(strip $(PROFILE)),$(PROFILE),cgi)"; INPUT_FILE="$(if $(strip $(INPUT_FILE)),$(INPUT_FILE),templates/references/cgi_source_example_fictional.docx)"; OUTPUT_FILE="$(if $(strip $(OUTPUT_FILE)),$(OUTPUT_FILE),templates/references/cgi_source_analysis.json)"; npx tsx scripts/analyze-template-docx.ts "$$PROFILE" "$$INPUT_FILE" "$$OUTPUT_FILE"'

.PHONY: uat-tenant
uat-tenant: ## Run tenant smoke flow once (TENANT=..., TARGET_COMPANY=...)
	@$(MAKE) smoke-tenant-e2e TENANT="$(if $(strip $(TENANT)),$(TENANT),_default)" TARGET_COMPANY="$(TARGET_COMPANY)"

.PHONY: uat-tenants
uat-tenants: ## Run the tenant smoke flow for _default then scalian
	@$(MAKE) smoke-tenant-e2e TENANT=_default
	@$(MAKE) smoke-tenant-e2e TENANT=scalian

# -----------------------------------------------------------------------------
# Docker registry
# -----------------------------------------------------------------------------

.PHONY: docker-login
docker-login:
	@echo "$(DOCKER_PASSWORD)" | docker login $(REGISTRY) -u $(DOCKER_USERNAME) --password-stdin

.PHONY: publish-api
publish-api: docker-login ## Push API image to registry
	@echo "Pushing $(REGISTRY)/$(API_IMAGE_NAME):$(API_VERSION)"
	@docker push $(REGISTRY)/$(API_IMAGE_NAME):$(API_VERSION)

.PHONY: publish
publish: publish-api ## Push API image to registry

# -----------------------------------------------------------------------------
# Scaleway Serverless deployment (decommissioned)
# -----------------------------------------------------------------------------

.PHONY: check-scw
check-scw:
	@if ! command -v scw >/dev/null 2>&1; then 		echo "scw (Scaleway CLI) not found. Installing..."; 		curl -sL https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh; 	fi

.PHONY: storage-status
storage-status: check-scw ## List Object Storage buckets in the configured region
	@scw object bucket list region=$(TENANT_S3_REGION)

.PHONY: storage-create
storage-create: check-scw ## Create the tenant Object Storage bucket in Scaleway
	@echo "Creating Object Storage bucket $(TENANT_S3_BUCKET) in $(TENANT_S3_REGION)..."
	@scw object bucket create $(TENANT_S3_BUCKET) region=$(TENANT_S3_REGION) acl=private

.PHONY: admin-hash
admin-hash: ## Generate ADMIN_PASSWORD_HASH and ADMIN_PASSWORD_SALT (PASSWORD="...")
	@if [ -z "$(PASSWORD)" ]; then 		echo "Error: PASSWORD is required (e.g. make admin-hash PASSWORD='change-me')"; 		exit 1; 	fi
	@node api/scripts/hash-admin-password.mjs "$(PASSWORD)"

.PHONY: legacy-serverless-disabled
legacy-serverless-disabled:
	@echo "Legacy Scaleway Serverless deployment has been decommissioned. Use .github/workflows/deploy-k8s.yml and k8s/ manifests."
	@exit 1

.PHONY: scw-create-namespace deploy-api-init deploy-api deploy wait-for-api dns-setup dns-api dns-ui dns-ui-legacy scw-custom-domain scw-custom-domain-legacy
scw-create-namespace deploy-api-init deploy-api deploy wait-for-api dns-setup dns-api dns-ui dns-ui-legacy scw-custom-domain scw-custom-domain-legacy: legacy-serverless-disabled

# Legacy Serverless metadata retained for audit only.
SCW_API_CONTAINER_ID ?= 10379fdb-ef44-4ceb-8630-5a22cc30827b
SCW_API_DOMAIN       = transposecv5ntjukr9-transpose-cv-api.functions.fnc.fr-par.scw.cloud
CUSTOM_API_DOMAIN    = cv-api.sent-tech.ca
CUSTOM_UI_DOMAIN     = cv.sent-tech.ca
LEGACY_UI_DOMAIN     = scalian-cv.sent-tech.ca

.PHONY: dns-info
dns-info: ## Show Kubernetes ingress DNS target information
	@echo "Kubernetes ingress host: transpose-cv.sent-tech.ca"
	@echo "Legacy Serverless DNS/custom-domain targets are decommissioned."

# -----------------------------------------------------------------------------
# Utilities
# -----------------------------------------------------------------------------

.PHONY: version
version: ## Show image version
	@echo "API_VERSION: $(API_VERSION)"

.PHONY: commit
commit: ## Create a git commit (MSG="type: message")
	@if [ -z "$(MSG)" ]; then \
		echo "Error: MSG is required (e.g., make commit MSG='docs: update spec')"; \
		exit 1; \
	fi
	@git commit -m "$$(printf "%b" "$(MSG)")"

.PHONY: exec-api
exec-api: ## Execute command in API container (CMD="...")
	$(COMPOSE_DEV) exec api sh -c "$(CMD)"

.PHONY: exec-ui
exec-ui: ## Execute command in UI container (CMD="...")
	$(COMPOSE_DEV) exec ui sh -c "$(CMD)"

.PHONY: storage-dev-bootstrap
storage-dev-bootstrap: ## Start local MinIO, create the dev bucket and seed tenant configs
	$(COMPOSE_DEV) up -d minio
	$(COMPOSE_DEV) run --rm minio-init
	$(COMPOSE_DEV) run --rm tenant-storage-seed

.PHONY: storage-dev-verify
storage-dev-verify: ## Verify tenant configs resolve from local MinIO
	$(COMPOSE_DEV) exec api sh -c 'npx tsx scripts/verify-s3-tenants.ts _default scalian draft'

.PHONY: uat-localhost
uat-localhost: ## Start the localhost stack with MinIO-backed tenant storage and run UAT
	@$(MAKE) up
	@$(MAKE) storage-dev-verify
	@$(MAKE) uat-tenants

.PHONY: tenants-migrate-s3
tenants-migrate-s3: ## Upload tenant registry/assets to S3 (SLUGS="_default scalian")
	@$(COMPOSE_DEV) exec \
		-e TENANT_STORAGE_BACKEND=s3 \
		-e TENANT_S3_BUCKET="$(TENANT_S3_BUCKET)" \
		-e TENANT_S3_REGION="$(TENANT_S3_REGION)" \
		-e TENANT_S3_ENDPOINT="$(TENANT_S3_ENDPOINT)" \
		-e TENANT_S3_ACCESS_KEY="$(TENANT_S3_ACCESS_KEY)" \
		-e TENANT_S3_SECRET_KEY="$(TENANT_S3_SECRET_KEY)" \
		-e TENANT_S3_PREFIX="$(TENANT_S3_PREFIX)" \
		api sh -c 'npx tsx scripts/migrate-tenants-to-s3.ts "$$@"' sh $(if $(strip $(SLUGS)),$(SLUGS),_default scalian)

.PHONY: tenants-verify-s3
tenants-verify-s3: ## Verify tenant configs load from S3 (SLUGS="_default scalian")
	@$(COMPOSE_DEV) exec \
		-e TENANT_STORAGE_BACKEND=s3 \
		-e TENANT_S3_BUCKET="$(TENANT_S3_BUCKET)" \
		-e TENANT_S3_REGION="$(TENANT_S3_REGION)" \
		-e TENANT_S3_ENDPOINT="$(TENANT_S3_ENDPOINT)" \
		-e TENANT_S3_ACCESS_KEY="$(TENANT_S3_ACCESS_KEY)" \
		-e TENANT_S3_SECRET_KEY="$(TENANT_S3_SECRET_KEY)" \
		-e TENANT_S3_PREFIX="$(TENANT_S3_PREFIX)" \
		api sh -c 'npx tsx scripts/verify-s3-tenants.ts "$$@"' sh $(if $(strip $(SLUGS)),$(SLUGS),_default scalian)
